question_data = [
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "RAM stands for Random Access Memory.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "AMD created the first consumer 64-bit processor.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Linux was first created as an alternative to Windows XP.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Android versions are named in alphabetical order.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
